// Generated by gencpp from file pkg_2/message_file.msg
// DO NOT EDIT!


#ifndef PKG_2_MESSAGE_MESSAGE_FILE_H
#define PKG_2_MESSAGE_MESSAGE_FILE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_2
{
template <class ContainerAllocator>
struct message_file_
{
  typedef message_file_<ContainerAllocator> Type;

  message_file_()
    : id(0)
    , name()
    , temp(0.0)
    , humidity(0.0)  {
    }
  message_file_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , temp(0.0)
    , humidity(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _temp_type;
  _temp_type temp;

   typedef float _humidity_type;
  _humidity_type humidity;





  typedef boost::shared_ptr< ::pkg_2::message_file_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_2::message_file_<ContainerAllocator> const> ConstPtr;

}; // struct message_file_

typedef ::pkg_2::message_file_<std::allocator<void> > message_file;

typedef boost::shared_ptr< ::pkg_2::message_file > message_filePtr;
typedef boost::shared_ptr< ::pkg_2::message_file const> message_fileConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_2::message_file_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_2::message_file_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg_2::message_file_<ContainerAllocator1> & lhs, const ::pkg_2::message_file_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.temp == rhs.temp &&
    lhs.humidity == rhs.humidity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg_2::message_file_<ContainerAllocator1> & lhs, const ::pkg_2::message_file_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pkg_2::message_file_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_2::message_file_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_2::message_file_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_2::message_file_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_2::message_file_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_2::message_file_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_2::message_file_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf2b034714b34baf5d9236109fd66779";
  }

  static const char* value(const ::pkg_2::message_file_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf2b034714b34bafULL;
  static const uint64_t static_value2 = 0x5d9236109fd66779ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_2::message_file_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_2/message_file";
  }

  static const char* value(const ::pkg_2::message_file_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_2::message_file_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string name\n"
"float32 temp\n"
"float32 humidity\n"
;
  }

  static const char* value(const ::pkg_2::message_file_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_2::message_file_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.temp);
      stream.next(m.humidity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct message_file_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_2::message_file_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_2::message_file_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
    s << indent << "humidity: ";
    Printer<float>::stream(s, indent + "  ", v.humidity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_2_MESSAGE_MESSAGE_FILE_H
