// Generated by gencpp from file light_robot/AddTwoNumResponse.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_MESSAGE_ADDTWONUMRESPONSE_H
#define LIGHT_ROBOT_MESSAGE_ADDTWONUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_robot
{
template <class ContainerAllocator>
struct AddTwoNumResponse_
{
  typedef AddTwoNumResponse_<ContainerAllocator> Type;

  AddTwoNumResponse_()
    : sum(0)  {
    }
  AddTwoNumResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::light_robot::AddTwoNumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_robot::AddTwoNumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoNumResponse_

typedef ::light_robot::AddTwoNumResponse_<std::allocator<void> > AddTwoNumResponse;

typedef boost::shared_ptr< ::light_robot::AddTwoNumResponse > AddTwoNumResponsePtr;
typedef boost::shared_ptr< ::light_robot::AddTwoNumResponse const> AddTwoNumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_robot::AddTwoNumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace light_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'light_robot': ['/home/khaled/auc/Day4 /catkin_ws/src/light_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_robot::AddTwoNumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_robot::AddTwoNumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_robot::AddTwoNumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::light_robot::AddTwoNumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_robot/AddTwoNumResponse";
  }

  static const char* value(const ::light_robot::AddTwoNumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int64 sum\n\
\n\
\n\
";
  }

  static const char* value(const ::light_robot::AddTwoNumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoNumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_robot::AddTwoNumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_robot::AddTwoNumResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_ROBOT_MESSAGE_ADDTWONUMRESPONSE_H
